services:
  - type: web
    name: sports-ecommerce-backend
    env: node
    plan: free
    buildCommand: cd backend && npm install
    startCommand: cd backend && npm start
    envVars:
      - key: NODE_VERSION
        value: 18.16.0
      - key: PORT
        value: 10000
      - key: MONGODB_URI
        value: mongodb+srv://Yashh-projects:yashvanth%40191104@cluster0.u27e8qb.mongodb.net/sports-ecommerce?retryWrites=true&w=majority
      - key: JWT_SECRET
        value: sports_ecommerce_secret_key_2026
      - key: STRIPE_SECRET_KEY
        value: your_stripe_secret_key_here
    autoDeploy: true

  - type: web
    name: sports-ecommerce-frontend
    env: static
    autoDeploy: true
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/build
    envVars:
      - key: REACT_APP_API_BASE_URL
        fromService:
          type: web
          name: sports-ecommerce-backend
          property: host
